import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/styles/globals.css';

const clashRegular = localFont({ src: '../fonts/Clash_Regular.otf' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${clashRegular.className} antialiased`}>{children}</body>
		</html>
	);
}
